name: Deploy to GitHub Pages

on:
  discussion:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # 只有当讨论是由仓库所有者创建时才运行
    if: github.event.discussion.user.login == github.repository_owner
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          go mod tidy

      - name: Build
        run: |
          npm run build
          go run main.go generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./content
          publish_branch: gh-pages