name: Disucssion to Post
on:
  discussion:
    types: [locked, unlocked, edited]

jobs:
  prepare_go_env:
    name: Setup go env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
      
  discussion_locked_or_edited:
    name: diuccsion locked or edited
    if: ${{ github.event.discussion.locked}} | ${{ github.event.discussion.edited }}
    - run: go main.go --action=modify --number=$Number
      env:
        Number: ${{github.event.discussion.number}

  discussion_unlocked:
    name: dicussion unlocked
    if: ${{ github.event.discussion.unlocked}}
    - run:  go main.go --action=unlocked --number=$Number
      env:
        Number: ${{github.event.discussion.number}