name: Disucssion to Post
on:
  discussion:
    types: [locked, unlocked]

jobs:
  post_to_hexo:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3
    
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: when diuccsion locked
      if: ${{ github.event.discussion.locked}}
      run: go mod tidy && go run main.go --action=modify --number=$Number
      env:
        Number: ${{github.event.discussion.number}}
        ACCSS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        USER_NAME: ${{secrets.USER_NAME}}
        SOURCE_REPO: ${{secrets.SOURCE_REPO}}
        TARGET_REPO: ${{secrets.TARGET_REPO}}
    
    - name: dicussion unlocked
      if: ${{ github.event.discussion.unlocked}}
      run: go mod tidy && go run main.go --action=unlocked --number=$Number
      env:
        Number: ${{github.event.discussion.number}}
        ACCSS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        USER_NAME: ${{secrets.USER_NAME}}
        SOURCE_REPO: ${{secrets.SOURCE_REPO}}
        TARGET_REPO: ${{secrets.TARGET_REPO}}