name: WhatIReadYesterday

on:
  workflow_dispatch:
    inputs:
      news:
        description: 'Yesterday News Summary'
        required: true
        type: string

  push:
    branches:
      - main
env:
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TIME_ZONE: Asia/Shanghai
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
          cache-dependency-path: "requirements.txt"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: WhatISawYesterday
        run: |
          source venv/bin/activate
          python what-i-read-yesterday.py "${{ inputs.news }}"